[profile.default]
src = "src"
out = "out"
libs = ["lib"]

remappings = ["@openzeppelin/contracts/=lib/openzeppelin-contracts/contracts/"]
#v4.9.6


# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options
[rpc_endpoints]
arbitrum_infura_api = "https://arbitrum-mainnet.infura.io/v3/${arbitrum_infura_api}"